# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1774fae68ab42e97ec62ae02966788f4d9cfda66f0bf9ff00c98a2ce275ec307317515db67a3cf8be0e4f0acd0319f01e21d9adb7f107d35ba8cd6aea020d72f

test:
  secret_key_base: 97830c6675ab8873a09bbb2f19917ea71ecb27f87299f3155f6e7f7e6f2c4fc68be300f2fe41b2432c611b87bb17da54701fb9ed6b2e1700de3aa3d5c91229bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
